### ISSUE TITLE
What do i do with the token

### ISSUE THREAD

**Issue by MeMasterMind** [Stanley-GF/discord-selfxss-token-grabber#2]
What to do with the token generated?
I mean what is that token thingy and how can i get discord nitro with that??

**Comment by Stanley-GF** [comment]
login :)

**Comment by MeMasterMind** [comment]
mai i know how, Im not into Discord APi that much 😅

**Comment by AmpPy** [comment]
> may I know how, Im not into Discord API that much 😅

use the login.js script and paste the token into


Login("token here");
